language: java

jdk:
  - oraclejdk8
script:
  - ant compile.module.helloworldtomcat.tests
  - ant compile.module.helloworldtomcat.production
  - zip -r helloworldtomcat *
  - mkdir -p travis_upload
  - mv helloworldtomcat.zip travis_upload/helloworldtomcat.zip
  - jar -cvf helloWorldTomcat.war *
  - mv helloWorldTomcat.war travis_upload/helloWorldTomcat.war

services:
  - postgresql

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    local_dir: travis_upload
    skip_cleanup: true
    bucket: mel-helloworld-bucket
    region: ap-southeast-2
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: mel-helloworld-bucket
    key: helloWorldTomcat.war
    bundle_type: zip
    application: HelloWorldTomcat
    deployment_group: fma-mel
    region: ap-southeast-2


