language: java

jdk:
  - oraclejdk8
script:
  - ant compile.module.helloworldtomcat.tests
  - ant compile.module.helloworldtomcat.production
  - zip -r helloworldtomcat *
  - mkdir -p travis_upload
  - mv helloworldtomcat.zip travis_upload/helloworldtomcat.zip

services:
  - postgresql